= Chapter One - Computer Forensics 

Computer forensics is a rapidly growing and changing field. There are many opportunities to apply the techniques we will discuss in this book. One does not need to desire to be a full time digital forensic investigator to benefit from the content of this book and the concepts of computer forensics. The ubiquity of computers in today’s society provides frequent opportunities to investigate the operation and content of devices in our everyday lives. Throughout this book I will use the term computer, but realize that any device that can create, modify, send, receive or store digital signals can probably be considered a computer. Because of the range of devices that one might investigate the term digital forensics is often used interchangeably with the term computer forensics. 
There are a significant number of types of computers in our lives. Many we don't even notice them as computers. Cell phones are a small portable computer. Digital video recorders, such as a TiVo®, are a specialized computer. Onboard computers in modern cars control and record actions of the driver and the automated prcesses of the car itself sucha s automated braking. The type of device can dictate how or what can be investigated, but any potential device can be a target of investigation in today’s society. 
The first task for learning any new topic is almost always a definition. Computer forensics is the collection, preservation and preparation of evidence contained inside a computer for presentation in court. 
My target audience for this book is students and technical professionals. Most of you will never prepare evidence for presentation for court proceedings. Any investigation could potentially lead to a criminal or civil proceeding. As an investigator you should always keep in mind that your actions could be scrutinized in the future, often time two or more years after your investigation, and may have a significant impact on an outcome of a trial. First and foremost, don’t panic. The process will be described and practiced throughout this book. No inspector is perfect in every investigation. The keys are going to be preparation, execution and documentation. We will examine all of these as we progress through this text. By reading this book and doing the labs you are working diligently on preparation. 
As a technical professional most investigations you conduct will not lead to any type of law suit or criminal case. They are most often identifying what has occurred to a system to repair any damage and prevention of a reoccurrence of the disruption to business. As a full time forensic investigator most of your cases will be pursued to be presented in court. A significant number of cases with substantial evidence are pled out before they are heard by a judge and jury. Collection, preservation and presentation of evidence are significant factor in this process. These are not the only types of investigations that could occur. While this is not an exhaustive list of organizations and types of investigations here are some that can benefit from a computer forensic investigation. 
Businesses might require investigating violation of company policies such as acceptable use of computers, sexual harassment or possible unauthorized access to corporate computers. 
Law enforcement investigates many potential types of crimes that involve computers. We will discuss this topic more throughout this book. 
Lawyers might require the services of a forensic investigator for civil cases such as stalking, harassment, divorce, or intellectual property infringement. 
Government intelligence agencies and military agencies conduct forensic examinations to collect and verify potential intelligence and information to support operations. 
Security firms frequently conduct forensic investigations for other organizations as part of incident response. They try to identify how intruders gained access to their systems or data, what they accessed and what data they might have exfiltrated. 
This list is far from exhaustive. In an introductory text we cannot cover all of these types of investigations and the nuances of each. Instead we will cover the most likely and most beneficial uses of computer forensics. In general, we will start with law enforcement processes and relate other common investigations to their practice. This the most logical approach. This is based on the fact that almost all investigations could ends up as law suits and their practices and philosophies work with almost all other types of investigations. Where relevant, the differences in the types of investigations will be noted for you to be aware of potential differences. 
Computers are used in crimes in three different ways. They are used in the commission of a crime and without a computer would not exist. Crimes like hacking fall into this category. Computers can be used in the commissioning of a crime that is still a crime without the existence of computers, but might make committing the crime easier. Crimes like harassment or fraud fall into this category. The last type of crime where computers are involved, computers act as a repository of information or evidence about a crime. Something such as a picture taken with a cell phone at the scene of a crime or a journal where someone details their crimes fall into this category. 
I also feel compelled to mention the use of a computer or peripheral as a physical object. Assaulting someone with a computer is often a question I receive in class when discussing this topic. Sometimes the question is a legitimate question, but most often it is in jest. This type of crime is not one we will discuss. This would be no different than a knife or brick as a weapon in an assault case. This is a more traditional forensic science, not digital forensics. 
We can relate these three types of crimes back to almost all of the other types of investigations. I will not usually talk about the types of crimes, but if I do they will often relate to more than just criminal cases. The sending of harassing messages via corporate email is not necessarily a criminal act, but is something a technical professional might be tasked to investigate. It falls under the second category, it is against the rules to harass fellow employees. This violation could occur in person, over the  phone, on paper or with the aid of a computer via email. 
Understanding computer forensics is all about understanding the process of identifying, preserving and presenting evidence. Your role as an investigator, whether it is a full time duty or as needed, is often as a leader or director versus a practitioner. You might be tasked to investigate a technology that you are not familiar with its internal working. This is not an impossible task. You likely won’t have the time or resources to learn the technology enough to investigate it properly. You will have to work with a 
subject matter expert to help navigate the technology and identify the best available evidence. Despite my years of experience in enterprise technology roles, education and forensic back ground, if I was tasked to investigate an Oracle® database, I would be lost. No investigator can be a subject matter expert in all technologies that you will be asked to investigate. 
Despite the fact that you don’t need to be an expert on the technology you are investigating, I have elected to use Microsoft Windows 7® as our baseline for learning computer forensics. It should help in the process of learning if you do not need to learn about the technology you are investigating as well. 
If you are not proficient in any current version of Windows® you may have to struggle with the additional burden of learning that operating system in addition to computer forensics. My justification for using a closed source, proprietary operating system to accompany a creative commons book is two-fold. The first is common usage. Windows® is still the most common operating system used by businesses. The second is that most technical professionals and technology students should be familiar enough with this technology to be able to focus on the computer forensic aspect of this book. 

I entertained using Linux® or Android® as they are both open source operating systems. In my experience as an instructor, far too few students are knowledgeable of these two operating systems for me to not spend time explaining the content of the operating system versus focusing on our true topic, computer forensics. 
In general, if you learn the computer forensics process and can understand one operating system, you can apply the process towards almost any technology. There are aspects or details that are unique to each technology that might require some new learning or techniques. The process to locating, preserving and presenting the evidence is still consistent through all technologies and type of investigations. 
The content of this textbook will focus on the technical aspects of building knowledge of digital forensics, understanding the process and developing the skills to build an environment to have a sound forensic process. I will not discuss specifics of computer based laws. I am not a lawyer and I cannot take into consideration every jurisdiction in the world where a potential reader might reside or investigate. 
I will however assume that you have a general knowledge of your legal system and you can understand basic legal terms. If you are not familiar or find terms you do not absolutely know, I strongly suggest you do some addition fact finding via sources such as Wikipedia or Youtube. 
I am also going to assume that you have some familiarity of investigations. It is also a reasonable leap that most people old enough to read in the United States have been exposed to certain types of investigate processes through popular media. I might make references or comparisons to physical evidence investigations and procedures. I will try to make the simple, understandable and not too graphic. If you have not been exposed to police shows or articles, most CSI, NCIS, or other police investigation shows are relatively accurate and informational. I can’t belive I just said “Go watch TV”, but I did. 
I will not discuss the ethics behind the topic of forensics investigations. While most laws are intended to reflect the ethics of the group that is subject to the law, the process isn’t always easy from an ethical perspective. Corporate investigations involve people’s livelihoods or might even send someone to prison for an action the perpetrator didn’t fully comprehend. You will be asked to do work that could very significantly impact a person or a business for the rest of their life. Worse yet, you might be asked to alter your findings to include or omit information based on the wishes and motives of your employer. 
At first glance laws and ethics might not seem significant. The more time I spent investigating the more these two influences led me to stop the practice of conducting investigations. I now teach other people to handle this burden in my place. 
The role of a digital forensics investigator is to find the evidence, preserve that evidence and present it to the person or group that requested in investigation. This is the long description. From here on I will summarize this process by using the phrase conducting an investigation or investigating. One thing I have noticed students struggle with is, they feel compelled to be the judge and jury. Avoid judgment and focus on collecting all of the relevant evidence for the appropriate people to judge. 
When I present the theory early in the course all students nod their head and agree that this is what should be done. At the end of the course when I read their findings, seldom is there a lack of bias or judgment. This is human nature to put the pieces together and form conclusions. You must resist this temptation. You will put your professional opinion into the investigation. You will interpret what you find and try to articulate what you think happened based on your knowledge of common computer usage. An easy example of this would be finding and email message in the sent folder of an email client. It would be my opinion that an email was composed and sent from that computer account at that date and time. I would not be able to definitively prove that a specific person wrote and sent the email unless I witnessed it. I would not comment on the content unless there quest a need to explain a technical aspect, such as it might have been stored in 64 bit code instead of plaintext. There might be other methods to associate a person with an activity, but most evidence you will find will not be absolute proof that any one person did any specific activity. Let the persons that requested the investigation make those decisions. Let the judge and jury do their job, focus on yours. 
