= Chapter 5 - Anti-Forensics and Data Hiding 
Most people who knowingly break the rules don't think they will get caught. This is also true for most computer users. The handful of rule breakers and troublemakers rarely take into consideration they might get caught. If they are careful enough to try and cover their steps. When these attempts at countermeasures are applied to a computer, it is generally considered to be anti-forensics. I like to use the term data hiding as it is often a more realistic description. 
The popularity of shows like NCIS, CSI and Criminal Minds have exposed most of the people you might investigate to some of the ways they might get caught or how investigators locate evidence. They might Google how to delete data or hide photos. In general, most computer users lack the technical understanding to truly prevent a successful investigation. 

When a person is using a computer and are worried, they might be caught doing something they shouldn't be they typically apply some common, simple protective measures. Often these measures will stop other simple users, but very few can avoid an educated investigator and standard forensic investigation software such as EnCase, FTK or Autopsy. 
The number of individuals that might take anti-forensic measures is small, I have often heard low single digit percentages. This small percentage might be some of the worst offenders or at the least, for most of us geeks, the exciting part of investigating. The presence of data hiding techniques is an evidence item in and of itself. It usually indicates that a user is doing something they know they shouldn't be taking measures to hide their actions. This might be significant for someone that has requested an investigation to determine if the person being investigated is acting intentionally. 

Data hiding or anti-forensics is also very commonly seen in incident response involving complex hacks. In this book I will not spend notable time discussing this portion of forensic investigation, it is a very rapidly growing career and high demand skill set. 

When we try to identify data hiding, we have multiple factors to consider. The first and most effective method is to understand the person being investigated. User skill level and motivations are the two most significant indicators of possible anti-forensics. Most users have limited knowledge of computers and how they operate beyond the normal use, such as web browsing and using applications. Some individuals have a much stronger understanding of how data is stored on a computer. The stronger their technical understanding the more likely they can identify advanced and effective techniques and apply them properly. Most individuals that break the rules are not facing prison time, at worst an upset spouse or supervisor. Their motivation is based on not getting caught and the severity of the penalty if caught might directly impact their effort to hide. Another factor in their motivation is the entity that they are preventing from locating their activities. If they are hiding data from a nosy neighbor or snooping spouse with basic computer knowledge, their efforts will be far different than trying to hide data from law enforcement. 

We might examine the average computer abuser. They call for help when their shortcut disappears because the application is “broken”. Their infraction might be using their work email to sign up for and use the web site Ashley Madison. They would rather risk their job than the wrath of their significant other if they are found out. 

My favorite example on the other end of the spectrum is Joseph E. Duncan III, convicted murder, kidnapper and child predator. Duncan studied computer science at North Dakota State University. He kept a journal of his act ivies for his own perverse reasons. He knew enough to encrypt the content with a strong passphrase to keep it safe from everyone, including the FBI. He had the knowledge of what and how to protect the information and the motivation to do so. 

Another indicator or limiting factor for the deployment of anti-forensics is the available resources. An advanced user can easily leverage tools to help hide data. The presence of software that is used primarily for data hiding is a clue for investigators that they need to keep their eyes open to possible anti-forensics. In law enforcement this might process might extend to warrant requests as well as altering search and seizure tactics. Some environments users might not have the luxury of installing software or using tools that require superuser permissions. This might not prevent the attempts to hide data, but it helps us to rule out certain types of data hiding. 
One of the last items to consider with anti-forensics is time. Does the person being investigated have the time to enact countermeasures? Does your investigation identify a timeline indicate or rule-out the likelihood of data-hiding? It is entirely possible that even if certain data-hiding techniques are possible, other supporting evidence eliminates the need to recover or unhide data if their actives and timeline can substantively provide adequate evidence. 
Passwords are the most common way for a computer user to try and hide data. Given their limited understanding of how data can be accessed, their belief that data is secured if hidden behind a password. In some instances, this is true, in other instances it is not true. It is directly related to the type of method of hiding that the password is associated with. 

The most prevalent password, or in the case of many portables a pin, is the operating system password. Microsoft Windows prompts users to create a password during initial setup of a computer. They encourage the use of an online account for several reasons. This action of setting up and account with a password doesn't indicate intent to hide data, but it can easily be leveraged for the purpose of perceived hiding. 
To a regular user, the data inside of a computer is only accessible if another person knows their password. In a home environment with only one enabled administrator account this may be closer to true if the computer and drive is only available through the operating system. Investigators do not use the operating system, except in cases where copying the drive might be impacted by encryption or failing equipment. We will use a third-party solution, hardware or software, to copy the drive or investigate it as a secondary drive using write blockers or bit-stream copies. Standard users do not know that the data on a drive can be accessed outside of the computer or via alternate boot method. 

Passwords can also be used to protect folders and files. Typically, this associated with a third-party application such as PGP, GPG, or 7-Zip to achieve password protection of a file or folder. These programs use encryption and provide a near-unbreakable protection of the protected files or folders. Without knowledge of the password or passphrase, properly applied encryption is undefeatable. A weak password or passphrase is the only feasible method to recover these items. These protected items might also still be present on the device in an unprotected state. Duplicate files are a common user mistake that defeats their encryption efforts. 
Folder and file encryption applied at the file system level is tied back to the operating system (OS) authentication. It can be effective at preventing unauthorized access, but is tied directly to the OS level password, which may be susceptible to password recovery software more readily than decryption attacks against applications such as PGP, GPG or 7-Zip. 
Passwords are also a method to protect files and applications. A program such as Peachtree Accounting to prevent users from opening a file without the correct password. The application may or may not include or incorporate encryption. It is dependent on the application and possibly the options selected during file creation or save time. Correctly implemented encryption will prevent recovery, other than weak password guessing or recovery. Most modern applications that include a password protection solution for privacy will include encryption. 

Most users will select a password that is easy to remember, such as something personal. It is likely that the password or a minor variant, such as the addition of a number to the end of the word, will also be present on the computer. Creation of a dictionary from the bit-stream copy is possible and advisable. FTK has a function integrated into the suite to generate a list of every string of characters between whitespaces to create a dictionary to guess passwords. 
Another common method of data hiding is file name and attribute manipulation. Users with general understanding of computer files can engage in several methods to hide data. Most of these methods are ineffective when investigated with common digital forensic tools. Users that are knowledgeable enough to deploy these anti-forensic countermeasures will frequently thwart other limited skill users. 

Power users with file attribute knowledge might employ a tactic known as file extension mismatch. The simple action of changing a file extension makes the file unusable on a Windows computer. The reason this effort is successful is rooted in how Windows associates files by their extension to a default application. A change of extension will change the default application that will attempt to open the file. A double click of a file will initialize the application that is associated with the extension of that file. If the application does not know how to open the true file type it will generate an error, and the contents of the file will not be displayed. A more skilled user can open the file with the appropriate application or rename the extension. Forensic software identifies the type of file based on the file header and compares the extension. If there is a mismatch the software will identify it as a potential item of interest. 

Additional methods used to hide files is to use the file system to identify files as hidden or system files. To an average user, these files would become invisible. A technically astute person would simply know how to unmask or unhide these files. Forensic investigation software ignores these attributes. 
A simple method of data hiding includes file naming and location. A deceptive name may throw off many nosy spouses or bosses. The ability to search by key words or examine dates accessed or modified help investigators to easily locate files of interest. 

A knowledgeable user may try to hide files by placing it in locations that other, non-technical users would not likely look. Locations such as the system directory or program files folder might be areas that will be safe hiding locations. Another common type of hiding includes creating multiple sub-folders from a common or uncommonly used folder. This approach often couples well with hiding files in locations with large numbers of similar files. A determined user may combine multiple methods to further hide files from other common users. 
Depending on the content or data that a motivated user might be trying to hide, embedding data or files into other existing files is a possible attempt. Data such as images can easily be embedded into text documents, presentations or archive files. They can be files created just to hide or files that had other purposes when created can be used to help hide from normal users. Investigation software helps to identify files by filtering by dates accessed, created, key word searches or file sizes. 

Common users as well as advanced users might use the ability to take their data with them to help hide it from prying eyes. Removable storage such as USB thumb drive is an easy method to take the evidence with you. This might not be a sign of hiding, so much as a method of convenience and control of their documents. This concept extends to cloud or online storage solutions. A note to examiners. Online storage is protected from investigation without a warrant or consent if it is a personal account. Even if an employee accesses it from a work computer on the work network, you cannot access their account legally without consent or search warrant. Frequently I have students that will discover a password for an online resource. They expand their search to include that online resource. Their actions are potentially criminal, violating the Computer Fraud and Abuse Act. 

More advanced techniques of data hiding include using specialized tools to place data into files or on unused locations of a storage media. The most discussed method is steganography. Hiding data in plain sight is a basic definition of steganography. The ability to place data into another file without modifying its appearance to the naked eye is not uncommon. Modern digital cameras embed metadata into images. The quality of the image is not impacted, but the data is easily viewed with metadata reading software. Steganography has a much more complex method. 

Almost any type of file can have data embedded into it using steganography techniques. To explain it I will give a simple explanation of how text might be embedded into a digital image without modifying the visible appearance of that image. A digital image has 32-bit color depth. A ten-megapixel camera has ten million 32-bit color dots. The human eye can identify color at roughly a 24-bit depth. The last eight bits have no impact or value to a person viewing the image. A program can simply overwrite the last eight bits with hidden data. You could potentially have 80 million bits to use for data hiding. This is a very simplified explanation, there are a notable number of potential issues, such as compression, that I will not factor into this basic explanation of steganography. Compression in modern digital image formats has an impact on applying this concept but doesn't prevent it. 
I have already covered this when discussing passwords, but encryption is worth a quick recap. Users with something to hide or a significant interest in protecting their privacy will select encryption to hide their data. Appropriately applied encryption with a strong passphrase is for all practical purposes undefeatable. Even with this fact, few people can use encryption to protect against entities like intelligence agencies and law enforcement. 
