= Chapter Two - Evidence Acquisition 
Evidence collection is a significant portion of a digital forensic investigation. Like most types of criminal investigations, digital forensics investigations have physical evidence. The unique aspect of computer forensic investigations is the digital evidence. You as an investigator have to address both aspects of an investigation, physical and digital. Each aspect has challenges, pitfalls and best evidence practices. 
Investigation Basics 
We will start with physical evidence aspects first. Acquiring or gaining access the devices that contain digital evidence is similar to other physical evidence. The most significant rule for both physical and digital evidence is “preserve the evidence” or to me “don’t modify the evidence”. Alteration of the evidence might create two potential issues in the investigation. 

First issue might be the destruction of information that might be valuable evidence. This might be a finger print or the email that has all of the details of a crime. The second issue involves the introduction of doubt of the validity of your evidence. If the person being investigated can generate doubt revolving around the accuracy of your findings, it might be considered as in accurate, fraudulent or outright dismissed as invalid evidence because it is tainted. 
If a crime scene has a bloody knife laying next to a corpse it is important that the knife not be altered. It might contain DNA evidence and finger prints of the perpetrator. If the person responding to the scene drops the knife into a bucket of industrial solvent, the evidence might be completely gone. If anything survives it is likely to be dismissed as tainted or not able to be verified as unaltered evidence. 
Similarly if you approach the computer used by a person alleged to be browsing pornography and it is logged on with the person in question’s account, you shouldn’t open a browser and check your Facebook account. The new files might overwrite older cached items, or the defendant might claim that this is how all of the evidence you found ended up on their computer, by your actions not theirs. This might be an obvious example, but similar pitfalls exist. 
When collecting physical evidence and when investigating digital evidence you need to have a legal right to do so. We will discuss this process and concept more in-depth later in this chapter, but remember this is not a legal guide or law book. If we are considering collection of evidence for an intelligence agency or military entity the situation might dictate and the rules resort to physical control is all that is needed to confiscate evidence with or without legal right. All other scenarios follow rules of search and seizure.In order to continue to discuss the acquisition and handling of physical evidence we will concede that you do have legal right to seize and search the evidence in question. 
If not modifying the evidence is rule number one for forensic investigators, rule number two is document everything you do in painful detail. This helps to prove that the evidence is the original unaltered evidence and helps to protect your reputation by providing a step-by-step recounting of your actions so that anyone else with the appropriate skills can recreate your findings. Even if you make a mistake, such as forgetting a step, you should keep detailed notes. Omitting an error indicates that you might be covering up other mistakes or intentional modifications of evidence or findings. You are a human being and will occasionally do something erroneous. If you admit to it, you are less likely to have your findings or the process questioned for accuracy and validity. 
As a general note to potential investigators, you will spend far more time documenting your actions than you will conducting the investigation. I generally use an 80/20 reference, but there are many variables involved. You will spend 80 percent of your time documenting and 20 percent of your time doing. Be prepared to become very verbose in your writing. Failure to be thorough in your documentation can cause evidence to become inadmissible, dismissed as potentially flawed or even call your competence as an investigator into question. Writing is an essential function to the investigation process. 

== Collecting Physical Evidence 
When collecting physical evidence the most important thing is to have a safe environment to be able to collect the evidence properly without any risk to you or anyone else. While this might not always be the case in all situations, where ever possible do not place yourself in danger to collect evidence. If you are part of a team executing a search warrant, ensure that the officers assigned to remove threats have done so. 
The first consideration once the area is secure and safe is to document the environment. All investigations should have a very specific purpose and scope. You should in your own words, as detailed as you can, describe the physical area you collecting evidence from. You might write it down with a pencil on a notepad, record it with a video camera, take photos or take audio notes dictating as you go. Ultimately it is best to have consistent, typed notes when you complete your investigation. Most important information will be specific details about the physical evidence and anything in the environment that is abnormal or notable. Abnormal or notable might help prosecutors to further document their allegations by associating the area with things that can be associated with the suspect. 
The unique aspects of physical evidence include details such as manufacturer, model, physical description such as color, stickers, damage, and customization. Serial numbers are an absolute essential when present as a unique identifier, but should not be the only identifier. For example, if the area is surrounded with images of Legos® and multiple building sets, this would indicate that the person who spends time in this area appears to be a fan of building blocks. You would make a note of this fact in as much detail as you can differentiate as possible. If you are conducting an investigation where other physical evidence will be collected, such as finger prints or foot prints, you need to ensure you wait for the individuals that will be collecting other physical evidence have completed that collection before you move forward. 

When collecting a computer you must access it before you seize it. If it is turned on and the user interface is visible, without creating any input that would modify the evidence observe any running programs or content. Document everything you see including the system time of computer with a comparison to another reliable device. If the computer is running the user interface blank, such as sleep mode, moving the mouse does not alter any volatile evidence or hard drive contents. If the mouse doesn’t make the computer resume, press the left or right direction arrow on the keyboard. If there is no display or you have documented everything visible you should remove the power cord from the back of the computer and if it is a laptop, pull the battery and unplug the power adapter. If it is a laptop and the battery is not removable, press and hold the power button until the system shuts down. If you know that the computer contains encryption or cannot be removed for any reason you will need to conduct a live investigation which will be discussed later in this book. 
Time is a very important aspect to the evidence items we will be collecting and analyzing. You should make every effort to document the system time. If the computer is powered on and the user interface is unlocked, check the logical location. In Windows(R), the clock is usually displayed in the system tray in the lower left hand corner of the screen. If the system is powered off or you forcibly shut the system down, you can collect the system time from the BIOS or UEFI without booting the operating system. If the system is off you should avoid at all costs of booting the operating system as it will modify the contents of the hard drive. 

Collection of physical evidence begins a process called the chain of evidence. It is imperative that all evidence once seized be kept in an environment where it cannot be accessed by unauthorized individuals. If unauthorized access is obtained to evidence an individual could alter, destroy or steal the evidence. As part of the chain of custody process a dedicated form is used to document where evidence is located and who has control of it at all times from the time it is collected until it is destroyed or returned to the rightful owner. A chain of custody form is needed for each evidence item. Additionally each item of evidence must be prepared or packaged to provide easy visible proof that it has not be tampered with or modified. 
The methods used for this can vary dramatically depending on the type of item and the resources available to the person seizing the evidence. Some investigators use specialized materials, such as tamper evident bags. Some investigators use brown paper bags, duct tape and a sharpie to seal an item. 
The purpose is to identify tampering, not prevent access. Physical security from unauthorized access is obtained by locked rooms, vaults, alarms, cameras, safes, personnel to monitor the evidence, or a combination of those solutions. 
Almost all of the forms, environments and processes in computer forensics are not standardized. There is no standard universal form used for documenting your investigation or one for chain of custody. There are many public documents made available by organizations like NIST and SANS that you can use or create your own. Creating a forensic investigation program from the ground up is a significant investment in time. 
A chain of custody evidence form typically tracks physical location, person who is protecting the evidence or transporting it, dates, times, and a description of the evidence item. It can contain other information, but these are a bare minimum. If you collect evidence and do not track it with a chain of custody form, a defender can easily argue that an evidence item was left unattended, accessible to anyone to modify the evidence. This then progresses to all negative evidence located were aledgedly planted by that unauthorized person. A chain of custody allows a paper trail to prove that the preceding scenario was not possible. Once you have successfully seized the equipment to be investigated it needs to be transported back to location where the investigations will take place. It is important that the individual transporting the evidence not leave it unattended. It should be secured where the transporter can see if anyone attempts to gain access to the evidence. Leaving it in a locked trunk and going out of line of sight is not keeping it secure. It can be left under the surveillance of a known trusted individual if it is documented in your notes. It is best practice to take evidence directly from the scene where it is seized to a secure location. 

The collection of evidence listed up to this point is the best possible scenario. There are some additional considerations that might need to be applied when seizing evidence. Volatility and availability of digital evidence is a significant consideration. If simply owning a hard drive was the crime, the instructions that precede this would always be perfect. There are some scenarios where exceptions are needed. 
If a suspect started running a program that was destroying data, it would be more important to stop that process first than to document the physical surrounding. If a computer’s hard drive is encrypted turning it off would prevent locating any evidence. If the computer being investigated is a company’s enterprise web server, under most circumstances you can’t unplug it and take it with you. We will discuss most of these scenarios more throughout this book. Under rare circumstances, collection of physical evidence might not be possible or viable. You might be forced directly to collection of digital evidence. 
The processing of the physical evidence which is not a container for digital evidence, such as a computer, is beyond the scope of digital forensics. We, as investigators, handle the physical evidence for collection and processing of the digtial contents. The steps between poscessing the physical and examining the digital contents can very dramatically on a case by case basis. The general process is usually similar. 

== Collecting Digital Evidence 

Investigators of digital evidence use specialized hardware and software to ensure that where ever possible rule number one, “Do not modify the evidence” is observed. The most common method used to apply this rule is the use of write blocking technologies. Write block hardware and write block software are manufactured by multiple companies and readily available in most jurisdictions including the United States. 
The effectiveness of the write blocker must tested and documented in a process known as validation. Validating hardware and software write blocking can be an involved and time consuming process. An investigator must test a known piece of evidence, such as a hard drive, proving that a write block device does not allow any alterations of the evidence. The testing process and the results are recorded and kept as record that the validation was conducted and proved the write blocking works as intended. 
Testing a USB to SATA write blocker might include connecting a known hard drive to your forensic workstation and attempting to modify files, delete files, copy additional files to the drive. The examiner will then verify after each documented attempt that the write blocker prevented any alteration of the digital evidence. We will discuss the use of hash values that assist in this process later in the book. 

The investigator documents the ability of each write block device or software before it is used to conduct an investigation. The validation of the technology only needs to be conducted before initial use or after significant change to the device or environment occurs. For physical hardware modifications such as a firmware update, inclusion of a new feature, use on a new workstation or dropping the device should prompt a new validation. A written, dated record is kept on hand or even included in each individual investigation report. 

The validation process is a written documentation that substantiates your efforts to prove your procedure does not modify the evidence. A failure to validate or prove you have validated your write blocking process may cause your process or the evidence to be drawn into question. This doubt may lead to your investigation or evidence being discredited or barred from admission in court. 

Investigating the original digital evidence is best conducted on a forensically sound copy of the original. Using the original evidence may lead to contamination, damage, destruction or loss of the evidence physically or the digital contents. Many devices or methods can be used to write block digital evidence. Once a method has been validated, creating a copy of the digital evidence for conducting your investigation where ever possible is important. 

Collecting evidence, processing evidence and investigating evidence all require structure to ensure that all cases and evidence are easy to identify and navigate. Naming of physical and digital evidence as well as the investigation cases need to be clearly named. Most organizations that conduct regular or frequent investigations use a naming convention. Using a sequential numbering is the most common method because it helps prevent confusion or exposing information about a case. Using names or types of investigations can lead to unintentional disclosure of information, confusion between cases and difficulty in storing cases long term. A naming convention that starts with calendar year followed by an incrementing number makes tracking and storing cases and their evidence easy. A case named 2015-0012 with evidence 2015-0012A is an example of a naming convention that facilitates ease of storage and retrieval. A case named 'Nielsen Porn' and evidence named hard drive might reveal too much information in a Human Resources investigation or lead to issues if there is another Nielsen investigated for browsing porn at work. Additionally most cases could contain a hard drive. Differentiating between 15 hard drives with no additional detail or differentiation is not easy. 

== Legal Right to Search and Seize 

It is important that we address this topic of legal search and seizure. I can't emphasize enough that, I am not a lawyer and this is not a legal text. This is not legal advice, it is technical advice. When in doubt, ask a lawyer. 

Investigating digital evidence can be a very involved task. It is in your best interest that before you seize anything or begin investigating you have the legal right to do so. I immediately think of the US Constitution and the Bill of Rights when this topic is brought to my attention. If you are assisting law enforcement with an investigation in the United States, they need to either have consent of the owner or a warrant issued by a judge to search or seize anything. An owner or possibly even a third party can consent to a search or surrender an item for seizure. This a very rigid principal with a few quirks and some interesting 'what ifs'. 
In the corporate world it is a little easier. All equipment and services provided by an employer is the legal property of the the employer; this includes the devices, such as computers, the network and network traffic, the files, the emails, the phone calls place over VoIP. The employer can surrender or has the legal right to examine for any or no right without the employee's knowledge or consent. There are a few rare and unlikely to encounter circumstances, but I will not even attempt to address or explain, where an employer cannot consent to or investigate the conents of their own equipment. 

If your employer tasks you with investigating a work computer, they have the legal right. If they ask you to examine network traffic, from their network, they have the right. They can surrender it to law enforcement without the employee's involvement or knowledge. It is wise to always ask for requests to investigate in writing. This helps protect investigators from allegations of wrong-doing if they are acting on the behalf of their employer. 

If you are involved in an investigation and it is discovered you didn't have the legal right to search or seize, all evidence collected and analized is not admissible in court. Additionally any derivitive evidence located because of the unlawful search is also inadmissable. This 

principle is known as fruit of the poison tree. If during your investigation of a hard drive you discover a location of additional hidden evidence that is a derivitive finding. If there was no legal right to search the hard drive, the additional evidence is also not legally investigated and cannot be used in a court proceding. 

This segment is far too brief to complete and adequately discuss legal right to search and seize. It is important to know that you as an investigator will need to be aware of legal issues surrounding search and seizure. I strongly encourage further learning on this topic beyond the scope of this book. 
