= Chapter 7 - Windows Artifacts 

One of the key aspects of investigation is locating the artifacts, or file remnants, that provide inculpatory or exculpatory; More simply put, if you find files that support or disprove the allegation you are successful in your investigation. Your job as an investigator is knowing where the files are in a Windows hard drive that will provide evidence. During your career, you may be asked to investigate many types of activities. Each case may have separate types of evidence files to locate or recover. In general, this is true for a Windows computer and just as true for an Android phone. Locating relevant files is the primary objective of investigating. 

For this book we are only including a small section related to Windows. The concepts and specifics can be applied to any other type of investigation. It is the intent to provide a basic understanding of process and details for a few basic evidence items so you as an investigator and learn more on your own as needed. The key to success is learning what files or locations contain the types of evidence you are seeking. General file structure knowledge and the ability to navigate folders is essential in almost all digital investigations. File types and locations can change based on the version of a software or operating system, so investigators must be ready to learn about a different environment with every investigation. 
It is important that you take the time before a real live investigation to learn how to locate the types of files and evidence you will need. This might mean doing a mock investigation before you start your real investigation. You don't want to 'learn as you go' because this can lead to errors, oversights or missed evidence. While you could under extreme circumstance 'learn as you go', but ensure you document everything in detail for your benefit. 

A very common item that might be involved in a Windows investigation are documents. In a simple case everything in a case would hinge on finding work related documents, such as MS Word documents or an MS Excel spreadsheet. Average computer users will have a default location they store their work documents. This might be in the Documents folder. When we investigate Ableforth, locating these files may be as easy as looking in 'C:\users\abelforth\documents\work' directory inside of our investigation software. 
The files located contain far more evidence that what we might first realize. A novice inspector will rush to view the contents, locate inculpatory evidence and stop investigating. They would be overlooking some very valuable information that helps support the case. Each file on a Windows computer has file system attributes. The important values are date and time created date and time last modified, and date and time last accessed. When we look at digital evidence from a computer, creating a timeline to associate a user with an activity or piece of evidence is vital to making the circumstantial evidence more substantive. 

MS Office documents such as MS Word and MS Excel embed a significant amount of information about the file. This metadata can also be a huge benefit to investigators. The metadata may contain the name or account name of the person that created the file, last modified the file, organization that registered the software when the document was created, modified dates and times, creation dates and times as well as changes made to the content of the document throughout the life of the document. 

As you locate artifacts you should mark them as important in your investigation software as well as document them in your notes. It is common to assign evidence numbers to each file located for easy reference. Some files may contain multiple items of interest. A good example might be a mailbox file from an email application such as MS Outlook. All of the emails sent and received are stored in a single file, such as ableforth.ost. Using appropriate software to open the .ost file might provide hundreds of emails relevant to the investigation. Identifying each one with a unique evidence number is a daunting task, but each email may have significance. Your job as the investigator is to locate as much evidence as you can to help the individual or group that requested the investigation make the most informed decision about proceeding with their duties and roles. Email and communications have some unique aspects that we will study in another section of this book. 

Windows has extensive logging capability. A computer can be configured to record actions or activities that take place on a computer automatically. Most corporate environments have specific types of events recorded by Windows for auditing and diagnostic purposes. Such as when a user account logs onto a Windows computer, an event is added to the security log. When a service is started, it is recorded in a log. A common type of evidence requested in corporate investigations, is examining for violations of work policies. This might be sexual harassment or using a computer for personal use. You may also be tasked to investigate to provide supporting evidence that an employee is not doing their assigned duties. The supporting evidence needed may be something as simple as examining the Windows security events and providing the dates and times a user's account logged onto the computer. You may be asked to examine web activity, which we will study in another section of this book. You may be tasked to identify if a user's account was used on a computer which was not authorized. Examining the security.evtx file in the 

'C:\windows\system32\winevt\logs' folder. It is imperative that the examiner know how to read and filter the content of the .evtx file. Locating a logon or logoff event takes some understanding and practice. There are many resources available to assist an examiner, but they shouldn't be 'learning as they go'. 
The last item we will examine in the Windows specific arena is the registry. Windows' registry is a database of computer and user specific settings and configurations. It was built as a single repository for configurations. It records many aspects of a Windows computer in one nice, neat location. 'C:\windows\system32\config\' hosts the files: SAM, SECURITY, SOFTWARE and SYSTEM. These files comprise the setting for the computer and some configurations that applied or accessed by all users of the computer. Each user has their own registry file NTUSER.DAT that stores their specific information. If we were examining Ableforth, his file would be 'C:\users\ableforth\NTUSER.DAT'. 
