= Investigating Digital Evidence 
Investigating the digital content of a computer is unique. The ones and zeroes previously discussed have a lot of frailty and challenges. Pioneers in this industry have helped us with tools and methodologies that take away most of the true challenges. We as investigators still need to understand what we are looking for and how to find it to be successful. When we simplify the much larger concept of digital forensics, we are talking about files and the tools to locate, open and view the contents of files. 

== Files 

The name 'file system' gives us the insight of the role of a file system. It helps a computer to store and locate files. Operating systems and applications are comprised of files. They both use files to store data to make the user experience more pleasant and useful. We as investigators cannot know every type of file ever created nor should we be expected to know every file included in the Windows(R) operating system. There are several informational items about files that can help us to better understand, locate and view the content of files where possible. 

== Structure 

All files have similar structures. They all have a beginning, content and an end. The content is what we most often seek to obtain. In a text document, the content is text of some type. The text might be a grocery list or a manifesto. The content may be easy to view or may require an application. Some files such as binary files are not intended to have to contents viewed, but instead are intended to be executed and perform some function, such as a calculator application. 

Files are typically identified as one of two types, binaries or data files. Binaries can be executables or dynamically linked libraries. They can be data files can be a vast number of possible types of files. Some common types of data files can include user created storage for an application, an archive of multiple files, or information for an application or operating system to use. 

When an operating system or application creates a new file, it uses the appropriate format for that specific type of file. The start of a file is the file header. The file header is unique to each file type. The first four or five bytes of a file identify the file type. In Windows(R), file types are identified by the extension of a file. The file example.bmp has an extension of bmp, a common digital image format. The first four bytes of a bmp file would be represented in hexadecimal as 42 4D F8 A9. This unique value is associated with bmp files. Operating systems such as Linux or MacOS associate a file by the header, not the extension. It is a common approach to examine the header of files in a forensic investigation. It helps in the data carving process as well as identifies file that might have been altered by an end user in an attempt to hide data from a casual user. Extension mismatch is the practice of changing a file extension in Windows(R) to prevent the correct application from opening a file. 

If we take the same example.bmp and rename it to example.docx, Windows(R) will try to open the file with Microsoft Word(R). The application will not be able to open the file properly and a casual user would think the file corrupted or broken. Most forensic investigation suites will identify the example.docx with the header of 42 4D F8 A9 as a mislabeled bmp file and likely highlight it for an investigator to examine as a suspicious file. 

Headers start a file, the content of the file the computer uses is in the middle and the End of File (EoF)sequences end a file. Most files have a simple EoF character. This character is also used in data carving. The carving process looks for the header and the EoF. The carving utility then takes everything in between and places it all back together as a single file. As discussed earlier, the process is not always reliable. The header and the EoF may be from two separate deleted files. The size of data in between header and EoF could be Terrabytes of data. 

== File Uniqueness 

Identifying or locating files and examining their contents is the key to a successful investigation. The ability to examine a file and determine when it was created, last modified, and to identify that it is a copy of an original file are all valuable pieces of information an investigator should collect during an investigation. Metadata is information about specific data. Metadata is created and stored in many ways in a computer. Information such as file creation date and time is generated and kept by the file system for every file. Information such as the make and model of a camera used to take a digital photograph can be embedded into the save image. This embedded data is also metadata. 

== Hash Values 

We discovered hash values in the Digital Evidence Chapter. Each 'chunk' of data has a unique hash value when a hashing function is applied to that 'chunk' of data. If the 'chunk' is modified in anyway, the hash value of the 'chunk' changes as well. This concept is true with files, folders and drives. 
Each file has a unique hash value. The most used hashing function is MD5 in the digital forensic industry. We established that we could use a hash value of a drive or file to prove it has not been modified. We can also use that idea to prove an unmodified file is not of interest to us as investigators or that the existence of a file that matches a known value is important. 
When a software publisher, such as Microsoft, releases an application or operating system, their software can be comprised of hundreds or thousands of individual files that are copied to your computer. The installed software has the exact same files for every installation. They will have the same hash values after every install. We can use a database of known files to hide files that came from the publisher and have not been altered. How that is achieved is different in each software suite, but most advanced forensics tools have identifying known files as an option. The National Institute for Standards and Technology maintains a database of known files from major publishers. This database is known as the National Software Reference Library (NSRL) and is available for free download. The NSRL is updated and published approximately every six months. 

The presence of a known bad or problematic file is also something that can be very beneficial to investigators. The gruesome example is the database maintained for law enforcement that contains hash values of all previously confiscated files containing child pornography. If the investigation suite has this database, the software can identify child pornography by hash value without having to view the contents of the offensive material. The same concept is often used for viruses and malicious software. 

The hash value of a file will be the same for every exact copy, even on different computers. The content of the file is the portion that is processed by the hashing function. Some of the metadata can be changed without altering the contents of the file. We can rename the file, and the hash value of the contents will remain the same. We can copy the file to another computer. This process will give the file a new created date on the target computer. This will not change the hash value either. 

== Metadata 
As previous mentioned files can have multiple types of metadata. The types and amount of metadata varies by the application that creates or modifies the file. 

There are two primary types of metadata that you will encounter. The first type is embedded in files the second type is created and maintained by file systems. When you start to look at files many of them have data embedded in them there are several types of metadata embedded there are descriptive metadata fields, technical metadata fields, and rights metadata fields. Descriptive metadata might contain information such as the title of the document, the author, creation date, and keywords. Technical metadata might contain information such as a file type, file format, resolution, bit depth, codec information.  Technical metadata might also include data such as program modified or created with, data rate, the model of a camera that took a picture, the GPS coordinates of where an image was snapped with a smartphone, file size, and time last modified. Rights metadata might contain copyright usage right licensing information and watermarking to identify ownership.

It is worth noting that some applications will modify file metadata as a method of tracking changes, such as MS Word documents the amount of time that a document has been opened for modifications or when it was last saved.  This is important to note as something as simple as viewing a document in a method that can read and write might modify the contents of a file.  In general, most metadata inside files is write-once read-many.  

File system metadata is generated and tracked by the file system in which the file resides.  Each file system tracks file information such as file name, logical location, physical location, file size, date and time created as well as date and time last modified.  Some file systems can be customized to track other data that the administrator identifies as important.  Most modern file systems also include data about ownership of a file, permissions to a file, dates and times accessed, and even tags or comments. 
One common question that I have received when conducting hands-on labs is “How can a file be modified before it was created?"  Based on file system metadata, a copy of a file from one disk to another is creating a new file at the time of the copy.  The file system may copy the remaining metadata of the original file.  If the file was modified yesterday and copied from drive C: to drive D: today, it was modified before it was created according to the file system.  This means that investigators must understand how to interpret metadata correctly.

== Investigation Tools 

Investigation requires specialized tools made for forensic investigation as well as non-forensic tools that can be used for forensic purposes.  We will discuss some of the most common tools used in the industry.  We will start with forensic suites of specialized software.  Multiple organizations have developed forensic suites that are used by law enforcement, government agencies, and private industry.  These suites are designed to be used by trained forensic investigators.  The suites are designed to be used in a forensically sound manner.  This means that the software does not alter the original data and that the software can be used to testify in court.  The suites are designed to be used in a forensically sound manner.  This means that the software does not alter the original data and that the software can be used to testify in court.  The suites are typically multiple tools that are integrated into a single interface to aid in the consistent and expedient investigation of digital evidence.  

=== Software for investigations

There are many software tools that can be used to investigate digital evidence.  Some of the most common tools are discussed below.  It is very important for students and potential practitioners to understand a few important aspects of digital forensic software and investigations.  Software is not a replacement for a trained investigator.  The software is a tool that can be used to assist in the investigation.  The software is not a magic bullet that will solve all problems.  Investigators should never learn how to use a software or conduct and investigation on a technology for the first time on a real, formal investigation. You may be forced to delay an investigation while you learn a software or environment you will be investigating by conducting practice investigations to develop a formal process, but in the long run it will preven mistakes or introduce the possibility that your skill and integrity into quesiton in court. 
It is also critical that investigators strictly adhere to software licensing.  Over my many years of instruction, I have had many students that have a dislike for comercial software.  They often ask if they can use a pirated version of the software.  The answer is always no.  If your invesgtigation would ever be used in legal proceeding all evidence could be ruled as inadmissible as it was obtained unlawfully or even potentially obtained illegally.  Futhermore, the investigators involved might be personally liable for copyright violations that could result in extremely large monitary penalties and potential criminal processecution.
The last item of noteworthiness is that not all tools used in a forensic investigation are designed to be used as forensic tools.  It is possible that some element of your investigation will require that you use non-forensic tools to conduct the investigation into a specific evnidence type.  This is not ideal, but it is a reality of the field.  It is important that you document the use of non-forensic tools and the results of their use.  This documentation will be critical if the investigation is ever used in a legal proceeding.

=== Forensic suites 

In this category we examine software that tries to provide a complete solution for digital forensic investigations.  The software is designed to be used by trained forensic investigators.  The software is designed to be used in a forensically sound manner.  This means that the software does not alter the original data and that the software can be used to testify in court.  The suites are typically multiple tools that are integrated into a single interface to aid in the consistent and expedient investigation of digital evidence.  Some of the most common forensic suites are discussed below.  In general the software in these categories have been validated and vetted in the legal system.  Expert technical witnesses have testified to the validity of the software and the results of the software.  Once a software and how it is used is on record as vetted by a technical expert, an investigator should not be questioned regarding the software and the results of the software.  This is a critical aspect of the forensic process.  The legal team only need to reference the prior case where the resutls were established as valid. 

The original commercially available digital forensic software was EnCase.  It was and in general is still considered to be the baseline for crimial investigations.  The software has evolved of the years and is now integraded with other case management tools owned by OpenText.  It can perform almost all typical forensic investigative tasks and has a large user base.  The software is expensive and requires training to use effectively.  The software is used by law enforcement, government agencies, and private industry.  The software is used to investigate a wide range of crimes and infractions. 

Another longstanding forensic suite is the Forensics Toolkit or FTK. AccessData developed FTK as a series of tools that were an early competitor to EnCase.  The software is also used by law enforcement, government agencies, and private industry. Similarly, it has merged into a larger bundle that includes case management tools and is now developed by eXterro Softare.  This software is also expensive.

Autopsy is an open-source forensic suite that can be used in lieu of the other expensive commercial forensic suites.  The software is free and has a large user base.  This suite does lack some features that are found in the commercial suites, but it is built on a framework that allows for anyone to develop and implement tools.  New tools might fall under scrutiny in a legal proceeding, but the software is still a viable option for many investigations.  Typically the creator of the tool would be called as an expert witness to testify to the validity of the tool and the results of the tool.  If you develop the tool and use it in an investigation, you would be the expert witness.

=== Specialty software

There are many types of tools available to assist in forensic investigations that are specialized for a specific type of investigation or evidence type.  Some of the most common types of tools are discussed below.  The following list is far from complete, but it does provide a good starting point for an investigator to begin to understand the types of tools that are available.

==== Browser software 

Many investigations might focus on a suspect's internet browsing activities.  There are specialty tools that can be used to examine a suspect's browsing history.  Since web browsing involves downloading and viewing of files from web servers, it would be logical that the files would be stored on the suspect's computer.  The files would be stored in methods consistent with the browser in question.  The larger suites listed above have tools that will look at individual files related to web browsing, but none of them provide a complete solution for web browsing.  The tools in this category are designed to provide a complete solution for web browsing investigations.  

==== Chat software

Some investigations might include chat conversations that occur on private or corporate networks.  There are specialty tools that can be used to examine chat logs.  The tools in this category are designed to provide a complete solution for chat log investigations.  The larger suites listed above have tools that will look at individual files related to chat logs, but none of them provide a complete solution for chat logs.  The tools in this category are designed to provide a complete solution for chat log investigations.

==== Text message software

some investigations might include text messages that occur on private or corporate networks.  There are specialty tools that can be used to examine text messages.  The tools in this category are designed to provide a complete solution for text message investigations.  The larger suites listed above have tools that will look at individual files related to text messages, but none of them provide a complete solution for text messages.  The tools in this category are designed to provide a complete solution for text message investigations.

== Investigative Hardware

The key element of digital forensic investigation hardware is the concept of read-only.  The effort to ensure that evidence is not modified, is achieved using write blocking technologies.  In general there are solutions for all types of media that an investigator might encounter.  An easy example of a media that might be investigated is a hard drive from a desktop computer.  Depending on the model the drive could be connected via SATA, SAS, IDE, USB, Firewire, Thuderbolt, PCIe, or even older interfaces depending on the age of the device being investigated.  It is commonplace to use a write blocker that is connected between the drive and the computer that is conducting the investigation.  The write blocker is a device that is designed to prevent any writes to the drive.  The write blocker is a critical piece of hardware that is used in every investigation.

It is also worth noting that an investigator will typically have a workstation that is build of commercial off-the-shelf computer parts in addition to the write blocking devices.

=== Forensic investigation workstations 

This is a dedicated computer that can be used to capture evidence, process the evidence, and investigate the case while adhering to forensic principles of not modifying the evidence.  It is possible on a limited budget to purchase a standard PC and use it as a forensic workstation.  The key is to ensure that the workstation is not connected to the internet and that the workstation is not used for any other purpose.  Collection or acquisition of evidence can be completed using a write blocker and a forensic suite.  The workstation can be used to process the evidence and investigate the case.  It is noteworthy that forensic suites process the bits on an evidence drive looking a all bits to identify data a low level to ensure all potential evidencie is identified.  This process is extremely time consuming and requires a powerful workstation.  Resources such as CPU, RAM, and GPUs are critical to the performance of the workstation.  It is not uncommon for workstations built for forensic investation to cost over $8,000.00 without any software.  I typically recommend that student look at 'F.R.E.D' from Digitial Intelligence as a good example of what a digital forensic workstation look like.

== Mobile Forensics

I have opted to keep this section separate.  Mobile devices are a unique challenge for forensic investigators.  The devices have a wide range of proprietary hardware and firmware.  Additionally as mentioned in the anti-forensic chapter, encryption can stop an investigation in its tracks.  Most modern cellphones are encrypted by default.  Therefore obtaining evidence from a locked device is extremely difficult.  The process of obtaining evidence from a locked device is called unlocking.  Few tools are available to unlock a device.  The primary solution in this area is Cellibrite.  It is an all-in-one solution that is primarily used by law enforcement and government agencies.  The software is expensive and requires training to use effectively. Cellibrite is selective as to who it will sell their solution. If an academic entity to aquire a Cellibrite solution, we are required to attend a trining bootcamp and purchase the device at retail cost in excess of $12,000.00 as of the writing of this text.  For this reason, we will not be discussing mobile investigations. 